version: "3.8"
services:
  # frontend:
  #   container_name: "frontend"
  #   build: ./frontEnd
  #   ports:
  #     - "8080:80"
  frontend:
    build:
      context: ./frontEnd
    ports:
      - "5173:3000"  # frontend: host 5173 → container 3000
    volumes:
      - ./frontEnd:/app
      - /app/node_modules

  backend:
    container_name: "backend"
    build: ./BackEnd
    ports:
      - "3000:3000"
    depends_on:
      - frontend
    volumes:
      - backend-db:/app/db

volumes:
  backend-db: