version: "3.8"
services:
  frontend:
    container_name: "frontend"
    build:
      context: ./frontEnd
      args:
        CRED_PATH: ${CRED_PATH}
        CRED_CERT: ${CRED_CERT}
        CRED_KEY: ${CRED_KEY}
        COUNTRY: ${COUNTRY}
        STATE: ${STATE}
        CITY: ${CITY}
        ORGANIZATION: ${ORGANIZATION}
        ORG_UNIT: ${ORG_UNIT}
        COMMON_NAME: ${COMMON_NAME}
    ports:
      - "5173:5173"
      - "8080:8080"
    volumes:
      - ./frontEnd:/app
      - /app/node_modules
      - certs-data:/certs
    depends_on:
      - backend
    networks:
      - app-network
    env_file:
      - .env

  backend:
    container_name: "backend"
    build: ./BackEnd
    ports:
      - "3000:3000"
    volumes:
      - backend-db:/app/db
      - ./uploads:/app/uploads
      - certs-data:/certs
    networks:
      - app-network
    env_file:
      - .env

volumes:
  backend-db:
  certs-data:

networks:
  app-network:
