version: '3.8'
services:
  frontend:
    container_name: "frontend"
    build: ./frontEnd
    ports:
      - "80:80"
  
  backend:
    container_name: "backend"
    build: ./BackEnd
    ports:
      - "3000:3000"
    depends_on:
      - frontend
    volumes:
      - backend-db:/app/db

volumes:
  backend-db: