version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=file:./dev.db
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "3000:3000"
    command: ["npm", "start"]

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend